### ISSUE TITLE
more links

### ISSUE THREAD

**Issue by netpipe** [fcambus/jsemu#109]
https://github.com/tecan/emscripten-projects has more links to emulators mainly 8086tiny and soon omega

**Comment by BigEd** [comment]
Are there live demo sites to link to? If you could list those, I can add links.  Otherwise, maybe a single mention of this portmanteau project would be appropriate.

**Comment by tecan** [comment]
http://www.netpipe.ca/apps/8086tiny/8086tiny.html

**Comment by BigEd** [comment]
Thanks - made an update. (The FreeDOS doesn't quite work for me - all output is doubled, or worse, and once in HELP I couldn't get out.)

**Comment by BakedCrossiant** [comment]
https://github.com/tjwei/pcsxjs - PCSX-Reloaded on the web

**Comment by hialmar** [comment]
Here is a JS emulator for the Oric computers:
https://github.com/pete-gordon/oricutron/tree/www
I'm currently ironing some bugs (file selectors aren't working)
You can try it here:
https://torguet.net/oric/Oricutron.html
With a tape loaded here:
https://torguet.net/oric/cyclotron/Oricutron.html
With a disk loaded here:
https://torguet.net/oric/aigle/Oricutron.html

**Comment by fcambus** [comment]
Added PCSXjs and Oricutron, thanks @BakedCrossiant and @hialmar!
