### ISSUE TITLE
Dead Links

### ISSUE THREAD

**Issue by PursiyMe7Seven** [fcambus/jsemu#119]
Amstrad: Roland
Commodore: c64js
DEC: PDP-8I emulator
Nintendo: NESNES
Sinclair: JtyOne Online ZX81 Emulator
Tandy: jTandy, redirects to ad
Early machines: WITCH Emulator

**Comment by fcambus** [comment]
Thanks for reporting this, I removed dead links and fixed what could be salvaged.

It seems JtyOne still works?

**Comment by PursiyMe7Seven** [comment]
I can't open it, I got "conection time exceeded" error.

**Comment by fcambus** [comment]
The JtyOne link still works for me, so closing this. Thanks again!
