### ISSUE TITLE
WASMpsx

### ISSUE THREAD

**Issue by Unzor** [fcambus/jsemu#120]
I made a fork of TJWei's PSX emulator to use for your own purposes, could you consider adding this?
https://github.com/Unzor/WASMpsx

**Comment by fcambus** [comment]
Your README says that it's a fork "to use for your own purposes.", but it's not clear to me what it means.

Could you explain the difference with tjwei/pcsxjs?

**Comment by Unzor** [comment]
Its difference is that you can embed it in your own site in an easy way, by downloading the ZIP file and using the wasmpsx.min.js. It also has less files than PCSXjs.

**Comment by fcambus** [comment]
Makes sense, thanks for the explanation. Added in 3faf44648d224757076ed8c00d601616fd8ddd0e, thanks!
