### ISSUE TITLE
Some emulators

### ISSUE THREAD

**Issue by Pixelsuft** [fcambus/jsemu#121]
- [halfix](https://nepx.github.io/halfix-demo/) [source](https://github.com/nepx/halfix/)
 - [basiliskII](https://jamesfriend.com.au/projects/basiliskii/BasiliskII-worker.html) [source](https://github.com/jsdf/macemu)
 - [qemujs](https://atrosinenko.github.io/qemujs-demo) [source](https://github.com/atrosinenko/qemujs)
 - [minivmac-em](https://www.gryphel.com/c/minivmac/index.html) [source](https://github.com/yksoft1/minivmac-em)

**Comment by fcambus** [comment]
Looks good to me, could you send a pull request to add all of them?

**Comment by fcambus** [comment]
Merged, thanks!
