### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by ethanaobrien** [fcambus/jsemu#135]
Would [this](https://github.com/ethanaobrien/emulatorjs) go on the list?

**Comment by BigEd** [comment]
Can you host it somewhere, maybe on github itself?  Then we can link to a working example.

Ideally, please make a pull request with the small edit to this repo.

**Comment by h57758** [comment]
I have a Pull Request for EmulatorJS #137

**Comment by ethanaobrien** [comment]
>Can you host it somewhere, maybe on github itself? Then we can link to a working example.
Ideally, please make a pull request with the small edit to this repo.

Sorry I must have completely missed the email. But yeah, @h57758's pr will close
