### ISSUE TITLE
Some more web emulators

### ISSUE THREAD

**Issue by Lamzas1234** [fcambus/jsemu#136]
https://playjs.purei.org/ - Play!js
https://skylersaleh.github.io/SkyEmu/ - SkyEmu
https://linoscope.github.io/CAMLBOY/ - CAMLBoy
https://kpspemu.github.io/kpspemu-demo/cube - kpspemu

**Comment by BigEd** [comment]
Looks good! Could you make a pull request for these?

**Comment by h57758** [comment]
I can do it if you want

**Comment by Forenzik-1989** [comment]
> if you want. I can make a pull request for you.

do it.

**Comment by h57758** [comment]
Done! #138

**Comment by BigEd** [comment]
Thanks!  Merged.  (Where possible, it's nice to have a link both to the emulator as a running webpage and also to the source page.)
