### ISSUE TITLE
what about cellular automata?

### ISSUE THREAD

**Issue by BigEd** [fcambus/jsemu#16]
In particular, Conway's Life is a favourite, and what better example than a simulated Turing machine, in Life, in JavaScript?
http://copy.sh/life/?pattern=turingmachine

Other Life implementations might be of interest:
http://pmav.eu/stuff/javascript-game-of-life-v3.1.1
http://rocha.la/javascript-conways-game-of-life

**Comment by fcambus** [comment]
While those are nice resources, I do not think those link have their places in this list as they are not machine emulators.

**Comment by BigEd** [comment]
OK!
