### ISSUE TITLE
Suggested Additions

### ISSUE THREAD

**Issue by nate2squared** [fcambus/jsemu#62]
Here are a few you can add if you like -

## Adventure Game Engines

* [Sarien](https://code.google.com/archive/p/sariendotnet/) - Sierra On-Line game emulator
* [Parchment](https://github.com/curiousdannii/parchment) - Infocom/Inform web interpreter
* [IFVMS](https://github.com/curiousdannii/ifvms.js) - Infocom/Inform web interpreter
* [ZZTJS](https://github.com/bstreiff/zztjs) - ZZT game engine
* [ZZTMMO](https://github.com/Marak/zztmmo) - Multiplayer ZZT game engine
* [ngPAWS](https://github.com/Utodev/ngPAWS) - Professional Adventure Writer (PAW) web interpreter

_Move Emscripten ScummVM from Miscellaneous to this section?_

## Miscellaneous

* [RockyJS](https://pebble.github.io/rockyjs/) - Pebble Watch interpreter/emulator

A JS retro game remake page would be good too! I'd be happy to contribute too.

_Nate_

**Comment by fcambus** [comment]
Hello,

Thanks for the suggestions. I started checking the links, I would say Sarien, ZZTJS, ngPAWS and RockyJS can go in. I would leave ZZTMMO out as it is abandoned, all links are dead and I'm not sure the code would still run with recent node versions.

For Parchment and IFVMS I need to check in more detail.

I like the idea of adding an adventure game engines section and to move Emscripten ScummVM in this newly created section. Do you want to submit a PR adding those links @nate2squared?

**Comment by fcambus** [comment]
Finally added the links, but left Sarien out as has it has recently been merged into ScummVM.

Thanks again for the suggestions.
