### ISSUE TITLE
Some East German 8-bit systems

### ISSUE THREAD

**Issue by floooh** [fcambus/jsemu#75]
Hi, I have 2 suggestions for somewhat exotic East German Z80 machines:

A KC85/3 and KC85/4 emulator written in JS by Alexander Lang (author of the Digger game): http://lanale.de/kc85_emu/KC85_Emu.html

And my own multi-system emulator for KC85/2,KC85/3,KC85/4,KC87,Z1013 and Z9001 (crosscompiled via emscripten): http://floooh.github.io/virtualkc/

I can provide a pull request, but was not sure where to sort these in :)

**Comment by fcambus** [comment]
Oh nice, I've read about the KC85 in the past and those machines looked very interesting.

I would gladly merge your pull request, you can put them in "Miscellaneous" or even better, in a newly created "Robotron / VEB Mikroelektronik" section.

**Comment by floooh** [comment]
Oki doki, I'll cobble a PR together in the evening :)

**Comment by floooh** [comment]
Closing this, since there's now the PR.
