### ISSUE TITLE
add em-fceux、em-dosbox

### ISSUE THREAD

**Issue by EtherDream** [fcambus/jsemu#87]

**Comment by BigEd** [comment]
Looking for info and links:

> FCEUX is a Nintendo Entertainment System (NES), Famicom, Famicom Disk System (FDS), and Dendy emulator

> em-fceux is an Emscripten port of FCEUX 2.2.2 emulator.

Repo: https://bitbucket.org/tsone/em-fceux
Demo site: https://tsone.kapsi.fi/em-fceux/ (seems offline)

**Comment by fcambus** [comment]
Em-DOSBox: https://github.com/dreamlayers/em-dosbox

**Comment by EtherDream** [comment]
em-fceux
![89e1fee7gw1f4px068l6xj21g0160qdh](https://cloud.githubusercontent.com/assets/1072787/23638272/8af8d70c-031b-11e7-9db9-0ae0dad1e048.jpg)

em-dosbox
http://playdosgamesonline.com/

**Comment by BigEd** [comment]
Did you mean to close this @EtherDream ?

We need to get from an issue to a pull request.

**Comment by fcambus** [comment]
@EtherDream @BigEd if any of you want to send a PR with those additions, go ahead :)

For Em-DOSBox I think we should use this link: https://github.com/dreamlayers/em-dosbox

**Comment by BigEd** [comment]
Will do, when I can summon the wherewithal!

**Comment by BigEd** [comment]
I'm getting a redirect loop for https://tsone.kapsi.fi/em-fceux/ @EtherDream
