### ISSUE TITLE
FRISCjs

### ISSUE THREAD

**Issue by mellowiz** [fcambus/jsemu#92]
Hi fcambus,
I've tried adding the following at the bottom of "Bare CPUs section":
...
@@ -147,6 +147,7 @@
 _- [jslm32](http://www.ubercomp.com/jslm32/src/) - JavaScript LatticeMico32 emulator running Linux ([Source](https://github.com/ubercomp/jslm32/))_
**+- [FRISCjs](http://ivanzuzak.info/FRISCjs/webapp/) - FRISCjs is a simulator of the FRISC processor written in JavaScript. FRISC is a simple, educational RISC processor developed at the University of Zagreb, Faculty of Electrical Engineering and Computing. ([Source](https://github.com/izuzak/FRISCjs))**
...

but, unfortunately, GH threw an error (I'm not exactly an expert).

Would you review my contribution, please?
Looks cool to me. I believe it'd be an interesting addition.

Sincerely,
Mel

**Comment by BigEd** [comment]
I've taken the liberty of adding an entry - hope it looks good to you, and to @fcambus - thanks for the suggestion!
