### ISSUE TITLE
Commodore 64 / Mega65 emulator

### ISSUE THREAD

**Issue by generalram** [fcambus/jsemu#93]
http://c65.lgb.hu/web-xemu/xc65.html

You might want to add this to your list.

Commodore 65 units are rare and selling for thousands on eBay. The Mega65 http://mega65.org/ Is trying to finish the C65 prototype as a functionally unit, with modern hardware modifications.

**Comment by BigEd** [comment]
Thanks - added. /cc @fcambus

**Comment by fcambus** [comment]
That's a nice addition, thanks for your submission @generalram!
